game.setLocalization("en_US","item.netherquartz.name","Quartz");
game.setLocalization("en_US","tile.netherquartz.name","Quartz Ore");
game.setLocalization("en_US","item.dark_steel.name","Black Steel");
game.setLocalization("en_US","item.wonderfulwands_wand_fire.name","Wand of Meteors");
game.setLocalization("en_US","item.elementsofpower.creative.name","Rainbow Diamond");
game.setLocalization("en_US","item.botania:mortarAndPestle.name","Magic Mortar");
game.setLocalization("en_US","item.modernmetals:uranium_crossbow.name","Small Pile of Uranium 238");
game.setLocalization("en_US","item.modernmetals:uranium_bolt.name","Small Pile of Uranium 235");
game.setLocalization("en_US","item.modernmetals:uranium_horsearmor.name","Raw Enriched Uranium");
game.setLocalization("en_US","item.bigreactors:ingotMetals.yellorium.name","Enriched Uranium Fuel Pellet");
game.setLocalization("en_US","item.bigreactors:ingotMetals.cyanite.name","Spent Nuclear Fuel");
game.setLocalization("en_US","item.bigreactors:ingotMetals.blutonium.name","MOX Fuel Pellet");
game.setLocalization("en_US","block.bigreactors:blockMetals.yellorium.name","Condensed Enriched Uranium Fuel Pellets");
game.setLocalization("en_US","block.bigreactors:blockMetals.cyanite.name","Condensed Spent Nuclear Fuel");
game.setLocalization("en_US","block.bigreactors:blockMetals.blutonium.name","Condensed MOX Fuel Pellets");
game.setLocalization("en_US","item.basemetals.mercury_powder.name","Cold Mercury Powder");
game.setLocalization("en_US","item.basemetals.mercury_ingot.name","Cold Mercury Ingot");
game.setLocalization("en_US","item.modernmetals:plutonium_horsearmor.name","Plutonium Powder");
game.setLocalization("en_US","item.modernmetals:plutonium_smallpowder.name","Small Pile of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_powder.name","Pile of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_ingot.name","Plutonium 238 Ingot");
game.setLocalization("en_US","item.modernmetals:plutonium_block.name","Block of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_bolt.name","Small Pile of Weapons-Grade Plutonium 239");
game.setLocalization("en_US","item.modernmetals:plutonium_crossbow.name","Small Pile of Reactor-Grade Plutonium 239");
game.setLocalization("en_US","item.techreborn.part.plutoniumCell.name","Raw MOX Fuel");
game.setLocalization("en_US","item.techreborn.part.doublePlutoniumCell.name","Pile of Weapons-Grade Plutonium");
game.setLocalization("en_US","item.techreborn.plate.coal.name","Dark Plate");
game.setLocalization("en_US","tile.silentgems:GemBlock0.name","Solid Mass of Ruby Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock9.name","Solid Mass of Sapphire Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock4.name","Solid Mass of Citrine Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock2.name","Solid Mass of Agate Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock15.name","Solid Mass of Quartz Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock14.name","Solid Mass of Serendibite Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock6.name","Solid Mass of Emerald Spell Dust");
game.setLocalization("en_US","tile.silentgems:GemBlock11.name","Solid Mass of Amethyst Spell Dust");
game.setLocalization("en_US","item.silentgems:Gem32.name","Supercharged Ruby");
game.setLocalization("en_US","item.silentgems:Gem41.name","Supercharged Sapphire");
game.setLocalization("en_US","item.silentgems:Gem36.name","Supercharged Citrine");
game.setLocalization("en_US","item.silentgems:Gem34.name","Supercharged Agate");
game.setLocalization("en_US","item.silentgems:Gem47.name","Supercharged Quartz");
game.setLocalization("en_US","item.silentgems:Gem46.name","Supercharged Serendibite");
game.setLocalization("en_US","item.silentgems:Gem38.name","Supercharged Emerald");
game.setLocalization("en_US","item.silentgems:Gem43.name","Supercharged Amethyst");
game.setLocalization("en_US","item.silentgems:Gem56.name","Supercharged Diamond");

game.setLocalization("en_US","enchantment.level.11","XI");
game.setLocalization("en_US","enchantment.level.12","XII");
game.setLocalization("en_US","enchantment.level.13","XIII");
game.setLocalization("en_US","enchantment.level.14","XIV");
game.setLocalization("en_US","enchantment.level.15","XV");
game.setLocalization("en_US","enchantment.level.16","XVI");
game.setLocalization("en_US","enchantment.level.17","XVII");
game.setLocalization("en_US","enchantment.level.18","XVIII");
game.setLocalization("en_US","enchantment.level.19","XIX");
game.setLocalization("en_US","enchantment.level.20","XX");
game.setLocalization("en_US","enchantment.level.21","XXI");
game.setLocalization("en_US","enchantment.level.22","XXII");
game.setLocalization("en_US","enchantment.level.23","XXIII");
game.setLocalization("en_US","enchantment.level.24","XXIV");
game.setLocalization("en_US","enchantment.level.25","XXV");
game.setLocalization("en_US","enchantment.level.26","XXVI");
game.setLocalization("en_US","enchantment.level.27","XXVII");
game.setLocalization("en_US","enchantment.level.28","XXVIII");
game.setLocalization("en_US","enchantment.level.29","XXIX");
game.setLocalization("en_US","enchantment.level.30","XXX");
game.setLocalization("en_US","enchantment.level.31","XXXI");
game.setLocalization("en_US","enchantment.level.32","XXXII");
game.setLocalization("en_US","enchantment.level.33","XXXIII");
game.setLocalization("en_US","enchantment.level.34","XXXIV");
game.setLocalization("en_US","enchantment.level.35","XXXV");
game.setLocalization("en_US","enchantment.level.36","XXXVI");
game.setLocalization("en_US","enchantment.level.37","XXXVII");
game.setLocalization("en_US","enchantment.level.38","XXXVIII");
game.setLocalization("en_US","enchantment.level.39","XXXIX");
game.setLocalization("en_US","enchantment.level.40","XL");
game.setLocalization("en_US","enchantment.level.41","XLI");
game.setLocalization("en_US","enchantment.level.42","XLII");
game.setLocalization("en_US","enchantment.level.43","XLIII");
game.setLocalization("en_US","enchantment.level.44","XLIV");
game.setLocalization("en_US","enchantment.level.45","XLV");
game.setLocalization("en_US","enchantment.level.46","XLVI");
game.setLocalization("en_US","enchantment.level.47","XLVII");
game.setLocalization("en_US","enchantment.level.48","XLVIII");
game.setLocalization("en_US","enchantment.level.49","XLIX");
game.setLocalization("en_US","enchantment.level.50","L");