game.setLocalization("en_US","item.netherquartz.name","Quartz");
game.setLocalization("en_US","tile.netherquartz.name","Quartz Ore");
game.setLocalization("en_US","item.dark_steel.name","Black Steel");
game.setLocalization("en_US","item.wonderfulwands_wand_fire.name","Wand of Meteors");
game.setLocalization("en_US","item.elementsofpower.creative.name","Rainbow Diamond");
game.setLocalization("en_US","item.runesofwizardry_pestle.name","Magic Mortar");
game.setLocalization("en_US","item.modernmetals:uranium_crossbow.name","Small Pile of Uranium 238");
game.setLocalization("en_US","item.modernmetals:uranium_bolt.name","Small Pile of Uranium 235");
game.setLocalization("en_US","item.modernmetals:uranium_horsearmor.name","Raw Enriched Uranium");
game.setLocalization("en_US","item.bigreactors:ingotMetals.yellorium.name","Enriched Uranium Fuel Pellet");
game.setLocalization("en_US","item.bigreactors:ingotMetals.cyanite.name","Spent Nuclear Fuel");
game.setLocalization("en_US","item.bigreactors:ingotMetals.blutonium.name","MOX Fuel Pellet");
game.setLocalization("en_US","item.modernmetals:tantalum_horsearmor.name","Black Diamond");
game.setLocalization("en_US","item.modernmetals:tungsten_horsearmor.name","White Diamond");
game.setLocalization("en_US","item.modernmetals:plutonium_horsearmor.name","Plutonium Powder");
game.setLocalization("en_US","item.modernmetals:plutonium_smallpowder.name","Small Pile of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_powder.name","Pile of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_ingot.name","Plutonium 238 Ingot");
game.setLocalization("en_US","item.modernmetals:plutonium_block.name","Block of Plutonium 238");
game.setLocalization("en_US","item.modernmetals:plutonium_bolt.name","Small Pile of Weapons-Grade Plutonium 239");
game.setLocalization("en_US","item.modernmetals:plutonium_crossbow.name","Small Pile of Reactor-Grade Plutonium 239");
game.setLocalization("en_US","item.techreborn.part.plutoniumCell.name","Raw MOX Fuel");
game.setLocalization("en_US","item.techreborn.part.doublePlutoniumCell.name","Pile of Weapons-Grade Plutonium");